changelog:
  categories:
    - title: Major Changes
      labels:
        - Semver-Major
    - title: Minor Changes
      labels:
        - Semver-Minor
    - title: Other Changes
      labels:
        - "*"