name: Create release

on:
  push:
    branches:
      - main
  workflow_run: 
    types:
      - completed
    workflows:
      - deploy_package.yml

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          
      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: 'deploy_package.yml'
          name: ConsoleApp
          path: ./
          
      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.12.0'
      
      - uses: gittools/actions/gitversion/execute@v0
        id: gitversion
          
      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          files: "**/*.exe"
          body: ""
          target_commitish: ""
        