name: Create release

on:
  workflow_run: 
    workflows:
      - 'Deploy Package'
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.workflow_run.event }}
          echo ${{ github.event.workflow_run.pull_request.base.ref }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
        
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/download-artifact@v4
        with: 
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.12.0'

      - uses: gittools/actions/gitversion/execute@v0
        id: gitversion

      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          files: "**/bin/Release/**/*.exe"
          generate_release_notes: false
        