name: Create release

on: 
  push: 
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: library
          path: .
      - uses: softprops/action-gh-release@v0.1.15
        with:
          files: "*.dll"
        