name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get tag version
        id: get_tag_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.get_tag_version.outputs.version }}
          name: "ConsoleApp-${{ steps.get_tag_version.outputs.version }}"
