name: Create release binary

on:
  release:
    tags:
      - '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$'

jobs:
  print_infos:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.release.tag_name }}
          echo ${{ github.event.release.published_at }}
          echo ${{ github.event.release.target_commitish }}
  create_release_binary:
    name: create release
    if: ${{ contains(github.ref, 'main') }}
    runs-on: ubuntu-18.04
    env: 
      VERSION_TAG: ${{ github.event.release.tag_name }}
      RELEASE_DIR: '/Release'
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: dotnet build --configuration Release --output ${{ env.RELEASE_DIR }}
      - uses: vimtor/action-zip@v1.2
        with:
          files: ${{ env.RELEASE_DIR }}
          dest: 'HyperPlan-App_${{ env.VERSION_TAG }}.zip'
      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.VERSION_TAG }}
          files: "HyperPlan-App_${{ env.VERSION_TAG }}.zip"