name: Create release

on:
  workflow_run: 
    workflows:
      - 'Deploy Package'
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - uses: actions/download-artifact@v4
        with: 
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: 'Release/'

      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.12.0'

      - uses: gittools/actions/gitversion/execute@v0
        id: gitversion
        
      - uses: vimtor/action-zip@v1.2
        with: 
         files: 'Release/'
         dest: 'ConsoleApp.zip'

      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          name: "ConsoleApp-${{ steps.gitversion.outputs.semVer }}"
          files: "ConsoleApp.zip"
        
