name: Create release binary

on:
  release:
    tags:
      - '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$'
    types:
      - published

jobs:
  create_release_binary:
    name: create release
    if: ${{ github.event.release.target_commitish ==  'main' }}
    runs-on: windows-latest
    env: 
      VERSION_TAG: ${{ github.event.release.tag_name }}
      ARTIFACTS_DIR: '.\Release'
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Build project
        run: dotnet build --configuration Release --artifacts-path ${{ env.ARTIFACTS_DIR }}
      - uses: vimtor/action-zip@v1.2
        with:
          files: '${{ env.ARTIFACTS_DIR }}\bin\ConsoleApp1\release'
          dest: 'HyperPlan-App_${{ env.VERSION_TAG }}.zip'
      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.VERSION_TAG }}
          files: "HyperPlan-App_${{ env.VERSION_TAG }}.zip"