name: Create release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: 'deploy_package.yml'
          name: library
          path: .
      - uses: softprops/action-gh-release@v0.1.15
        with:
          files: "*.dll"
        