name: Deploy package

on:
  push:
    branches: 
      - main
      - develop
  pull_request: 
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build project
        run: dotnet build --configuration Release
      - name: publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: ConsoleApp
          path: '**/bin/Release/**/*.exe'
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.*
          source-url: https://nuget.pkg.github.com/dannyneup/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PACKAGE_REGISTRY_TOKEN}} 
          
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release
        working-directory: ./ConsoleApp1

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./ConsoleApp1/bin/Release/*.nupkg --api-key ${{secrets.PACKAGE_REGISTRY_TOKEN}}